### ISSUE TITLE
Running standalone with Kinect and openni_launch

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_perception_people#115]
I'm trying to set this up for a student with the released version of the tracker etc. The computer we have access to has an old Kinect. We are running this with `openni_launch` rather than `openni_wrapper` as the latter doesn't seem to produce output, but the former does. When I run the standalone tracker, I don't get any output on `/mdl_people_tracker/image` or `/mdl_people_tracker/people_array`. 

I am using the following launch commands:

```
roslaunch openni_launch openni.launch
roslaunch perception_people_launch people_tracker_standalone.launch load_params_from_file:=true
```

Looking at the README on the launch page it looks like all the default values should work. 

The rosgraph looks ok too.

![rosgraph](https://cloud.githubusercontent.com/assets/927289/5183513/a3d0c9a6-74a7-11e4-9cbf-70ef3ffd1fca.png)

Any idea why things aren't producing output?

**Comment by hawesie** [comment]
I've looked back at #89 but it seems like the issues I had with parameters have changed now.

**Comment by cdondrup** [comment]
The main difference between the openni_wrapper and the openni_launch is the name of the depth topic it subscribes to. This is also missing in the graph. Try to run it with `depth_image:=/depth/image` or `depth_image:=/depth/image_rect` because the default topic for the wrapper is `/depth/image_rect_meters` which doesn't exist within the openni_launch.

In general the topic name is made from `camera_namespace` which defaults to `/camera` in the standalone version plus `depth_image`. So just running 

```
roslaunch perception_people_launch people_tracker_standalone.launch depth_image:=/depth/image
```

Should work. Maybe I should mention that in the beginning of the readme somewhere instead of just in the description of the parameter.

**Comment by hawesie** [comment]
Awesome, that works. Sorry for the bother, but the params and namespaces looked superficially correct enough that my brain didn't kick in. So, to confirm I have a successful standalone system with released packages running just:

```
roslaunch openni_launch openni.launch
roslaunch perception_people_launch people_tracker_standalone.launch depth_image:=/depth/image load_params_from_file:=true
```

Subscribing to `/mdl_people_tracker/image` in rviz shows the output.
