### ISSUE TITLE
Too many false positives

### ISSUE THREAD

**Issue by gestom** [strands-project/strands_perception_people#46]
The pedestrian detector often reports people in the scene even if there are none.
Running the PD over the Lincoln dataset gives more than 50% of false positives.

**Comment by marc-hanheide** [comment]
@dennismitzel, is there anything we can do about this??? @cdondrup, do you know any parameters?

**Comment by cdondrup** [comment]
@dennismitzel is working on that at the moment. So far, he cleaned up config files and documented them so that we know what the parameters are doing. He will also put together a description of the functionalities and current limitations of the tracker over the next days.
As soon as I had the time to test the new set-up I will create a pull request.

**Comment by hawesie** [comment]
Closable?

**Comment by cdondrup** [comment]
Since this is ages old, we are are using a different tracker now, and I don't have hope in @dennismitzel still working on this, I'll close it.
