### ISSUE TITLE
Create release version without HOG

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_perception_people#85]
Since the whole HOG feature library is still privately hosted by Aachen, I think that the people perception should be release without the optional HOG feature detector.

Another possibility would be to catkinize it and host it on our ppa if possible. Since this generates more work, I would suggest it for future releases.

**Comment by ghost** [comment]
I'm not completely the expert here, but I think the CudaHOG stuff was written by Patrick Sudowe and has been open source since I knew it. Is there another HOG related library I missed? As far as I know it is also again included in the latest release of the tracker, so that should be fine. But again, since I'm not dealing with the whole people stuff here, it might be something to discuss with Bastian.

**Comment by cdondrup** [comment]
The only problem is that it has to be a ubuntu or ros package in order to be included in our release. If it cannot be resolved by rosdep, it doens't work. That means, correct me if I'm wrong @marc-hanheide, we would either have to host a ros version of it or it would have to be in the official ubuntu repositories. Therefore, I think it is best to start with a version without the HOG as we are not using it currently anyway.

**Comment by lucasb-eyer** [comment]
I'm ok with not including it: less work and nobody used it. When somebody will need it, he'll have to add it. CudaHOG (actually called GroundHOG) is GPLv3 licensed anyways...

**Comment by marc-hanheide** [comment]
Just to say: It's not to hard to include such 3rd party libs in the process: http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty I suggest to actually do so, if there are no other objections

**Comment by cdondrup** [comment]
Closed via b10888f804b49664edd4c9a9cf442fda65773d10 and f76882f0bdfdef876f40dded49396f3de0af1c03
